# Generated by Django 5.0.2 on 2024-02-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_user_remove_projectteam_user_projectteam_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.ForeignKey(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Canceled', 'Canceled'), ('Active', 'Active'), ('Priority', 'Priority')], on_delete=django.db.models.deletion.CASCADE, to='project.status'),
        ),
    ]
