# Generated by Django 5.0.2 on 2024-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectmodule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status_id',
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Canceled', 'Canceled'), ('Active', 'Active'), ('Priority', 'Priority')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
