# Generated by Django 5.0.2 on 2024-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_task_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_Minutes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_util_minutes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
