# Generated by Django 5.0.2 on 2024-03-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_task_estimated_minutes_task_total_util_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='total_util_minutes',
        ),
    ]
