# Generated by Django 5.0.2 on 2024-03-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_usertask_total_util_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskstatus',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Done', 'Done')], max_length=100, null=True),
        ),
    ]
