# Generated by Django 5.0.2 on 2024-03-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
