# Generated by Django 5.0.2 on 2024-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
