# Generated by Django 5.0.2 on 2024-02-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
