# Generated by Django 5.0.2 on 2024-02-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userImage',
        ),
    ]
