# Generated by Django 5.0.2 on 2024-02-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userImage',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
